### ISSUE TITLE
GitHub config notes: reporting content

### ISSUE THREAD

**Issue by andyblundell** [NHSDigital/software-engineering-quality-framework#205]
Another good candidate for org-level default settings, possibly:

https://docs.github.com/en/communities/moderating-comments-and-conversations/managing-reported-content-in-your-organizations-repository

_Originally posted by @andyblundell in https://github.com/NHSDigital/software-engineering-quality-framework/issues/166#issuecomment-946001420_

**Comment by iw-ezequiel** [comment]
Closed by #212
