### ISSUE TITLE
Add worked examples for code repository commit signing

### ISSUE THREAD

**Issue by patrickmoore-nc** [NHSDigital/software-engineering-quality-framework#273]
Signing commits can be quite tricky. Providing clear worked examples can reduce inertia to set this up. Furthermore the reasons for enforcing signing are not well understood, even among developers.

Some of these patterns have been built in the CCOE, so sharing them here in a generic way can facilitate adoption of these quality standards.

**Comment by stefaniuk** [comment]
That's a very good suggestion @patrickmoore-nc 

We have some guidelines and working examples/scripts. One of them is located here https://github.com/nhsd-exeter/make-devops/blob/main/documentation/Contributing.md#signing-your-git-commits

Is this the level of detail that we would like to see in the framework?

**Comment by stefaniuk** [comment]
👍 I'm just looking at your PR.

**Comment by patrickmoore-nc** [comment]
Does the markdown pass validation now?

**Comment by stefaniuk** [comment]
There are about a dozen linting warnings coming from the `nhsd-git-secrets/README.md` file. Would you mind having a look, please? 

The way the liner works is that it validates the whole file that has been changed as part of the PR. These issues may have been created in the past by someone else. I suspect this is the case - not your changes. However, our intention is to fix these as we go. Hope you are ok with that?

**Comment by stefaniuk** [comment]
PR #274 merged
