### ISSUE TITLE
Post mortems after service outage

### ISSUE THREAD

**Issue by arctangent** [NHSDigital/software-engineering-quality-framework#47]
Regarding https://github.com/NHSDigital/software-engineering-quality-framework/blob/master/practices/service-reliability.md

Suggested addition:
It is good practice to conduct a post mortem after any service outage or significant degradation, with the goal of identifying improvements to systems and processes (rather than apportioning blame).

**Comment by andyblundell** [comment]
https://github.com/NHSDigital/software-engineering-quality-framework/pull/52

(@arctangent I've invited you to the NHSD organisation so I can add you to code reviews)
