### ISSUE TITLE
Plan to keep up to date

### ISSUE THREAD

**Issue by arctangent** [NHSDigital/software-engineering-quality-framework#49]
Regarding https://github.com/NHSDigital/software-engineering-quality-framework/blob/master/practices/cloud-services.md

Ref "Keep up to date"

Very often when a new service is commissioned there is a failure to identify, plan, and charge for the entire systems development life cycle - including maintenance, periodic re-platforming, and the eventual decommissioning.

I'd suggest we put in something to ensure that these things are considered at the outset (or at least ASAP retrospectively) so that programme roadmaps can be adjusted and so that necessary resource (human and financial) can be identified well in advance.

**Comment by stefaniuk** [comment]
Re the second part of your comment - can this be achieved as an outcome of a healthy tension between product and engineering?

**Comment by arctangent** [comment]
It's definitely not just an engineering concern. Maybe the point needs emphasising somewhere else, like a doc that explains the roles and responsibilities of different stakeholder groups in the development process.

**Comment by ivorc** [comment]
It sounds like a good point, @arctangent, but I'm not sure it fits in the quality framework. The point that you need to do it is here in the item you commented on; the project funding arrangements seems sufficiently far removed from engineering principles that it feels like a conversation for elsewhere. Do you agree? Are you OK to close this one?

**Comment by arctangent** [comment]
Happy to close. I will try to bring this up somewhere more appropriate at a
later date.
