### ISSUE TITLE
The term "3 amigos" is causing some confusion

### ISSUE THREAD

**Issue by andyblundell** [NHSDigital/software-engineering-quality-framework#66]
This term is used in a couple of different ways in NHSD. Would be useful to explain what we mean by it in this context.

**Comment by arctangent** [comment]
Yes I think it would.

"Three Amigos" is a phrase/term that a lot of people use without thinking about what it really means, and this can sometimes defeat the object - for example there don't have to be only 3 people involved, and only having 3 people could be an oversight!

The fundamental point of "Three Amigos" is that a change should be examined throughout its lifecycle from different perspectives. These may be the typical BA/Dev/QA triad or, depending on the change, you might want experts from Infra, Accessibility, Security etc. involved.

I wish we had a better name for what we meant by this sort of critical examination...

**Comment by andyblundell** [comment]
Closing based on PR110
